version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - echo exported build number is : $CODEBUILD_BUILD_NUMBER
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
    - location: scripts/start_server
      runas: root
    - location: scripts/move_index
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      runas: root
