version: 0.2
phases:
  build:
    commands:
      - pwd
      - ls -la
#       rspec HelloWorld_spec.rb
      - echo build number is $CODEBUILD_BUILD_NUMBER 
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 
