#!/bin/bash
old=$(ls /var/www/html/ | grep index.html | head -n 1)
now=$(date +'%d_%m_%y')

if [ $old == "index.html" ]; then
        echo "index file already exists moving it to backups..!"
        mv /var/www/html/$old /git/index_backup/index_$now
else
        echo "Deploying the index file"
fi
